version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: migrate_service
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgres://user:password@db:5432/orders_db?sslmode=disable", "up"]
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations

volumes:
  db_data: